name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: nstall dependencies 
      run: |
        sudo apt-get update
    - name: make
      run: make